name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: Give a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: at-what-step-broke
    attributes:
      label: At which step did the bug/issue show up?
      description: Go into detail at which step in the testing process the bug/issue showed up,
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our Remote are you running?
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Fill out the os environment the bug/issue showed up in.
      value: |
        1. Browser and Version: 
        2. OS: 
        3. Viewport Size: 
      render: bash
  - type: input
    id: sourceurl
    attributes:
      label: Source URL
      description: What is the url where the bug/issue showed up?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. \n Can be accessed by clicking Ctrl + Shirt + I together in Chrome/Edge
      render: shell
  - type: dropdown
    id: severity
    attributes:
      label: What's the severity of the bug?
      options:
        - critical
        - major
        - minor
        - trivial
    validations:
      required: true
